apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fiat-bridge.fullname" . }}-secrets
  labels:
    app.kubernetes.io/name: {{ include "fiat-bridge.name" . }}
    helm.sh/chart: {{ include "fiat-bridge.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.secretEnv.dbPassword | b64enc | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.secretEnv.awsAccessKeyId | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secretEnv.awsSecretAccessKey | b64enc | quote }}
